theme: jekyll-theme-hacker
title: Marc Fouquet
description: |
   IT-Security, Fotografie
   Instagram: <a href="https://www.instagram.com/marc_fouquet_foto/">marc_fouquet_foto</a>
   Instagram Makrofotografie: <a href="https://www.instagram.com/marc_fouquet_2/">marc_fouquet_2</a>
   
